/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package availableAppoinments;

import com.formdev.flatlaf.FlatIntelliJLaf;
import static common.CommonFunctions.getSelectedBirthDate;
import home.HomeForm;
import home.HomeFormDoctor;
import home.HomeFormReceptionist;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logIn.LogInForm;
import logIn.UserDao;
import static validation.Validation.txtFieldValidation;

/**
 *
 * @author Achinthya Dulshan
 */
public class createAppoinment extends javax.swing.JFrame {

    /**
     * Creates new form createAppoinment
     */
    AvailableAppoinment newAvailableAppoinment = new AvailableAppoinment();
    AvailableAppoinmentDao dao;
    private String userRole = UserDao.logInUser.getRole();
            
    public createAppoinment() {
        initComponents();
        
        dao = new AvailableAppoinmentDao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtMedicalStaffId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();
        txtStartTime = new javax.swing.JTextField();
        txtEndTIme = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add Appoinment Time ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 410, 70));

        jSeparator1.setForeground(new java.awt.Color(255, 204, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 880, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Doctor ID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 90, 30));

        txtMedicalStaffId.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMedicalStaffId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMedicalStaffIdKeyReleased(evt);
            }
        });
        getContentPane().add(txtMedicalStaffId, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 320, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Start Time :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("End Time :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, -1, -1));

        txtDate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 320, -1));

        txtStartTime.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtStartTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStartTimeKeyReleased(evt);
            }
        });
        getContentPane().add(txtStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, 320, -1));

        txtEndTIme.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtEndTIme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEndTImeKeyReleased(evt);
            }
        });
        getContentPane().add(txtEndTIme, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 470, 320, -1));

        btnAdd.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnAdd.setText("Add to Appoinments");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 570, 250, 50));

        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel11.setText("Medical Center Management System");
        headerPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 228, -1));

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/close.png"))); // NOI18N
        btnClose.setToolTipText("Close Application");
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        headerPanel.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 30, 30));

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/logout.png"))); // NOI18N
        btnLogOut.setToolTipText("Log out");
        btnLogOut.setBorder(null);
        btnLogOut.setBorderPainted(false);
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        headerPanel.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 30, 30));

        getContentPane().add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnHome.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/home.png"))); // NOI18N
        btnHome.setText(" Return to Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 371, 300, 50));

        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrounds/makeAppoinmentV2.png"))); // NOI18N
        getContentPane().add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkPrivillage() {
        if (userRole.equals("reception")) {
//            btnShowPatientDetails.setVisible(false);
        }
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        
        newAvailableAppoinment.setMedical_staff_id(txtMedicalStaffId.getText());
        newAvailableAppoinment.setDate(getSelectedBirthDate(txtDate));
        newAvailableAppoinment.setStartTime(txtStartTime.getText());
        newAvailableAppoinment.setEndTime(txtEndTIme.getText());
        
        String errors = checkErrors(newAvailableAppoinment);
        
        if (errors.equals("")) {

            // if it doesn't have empty field 
            // insert to database and give message
            dao.addAvailableAppoinment(newAvailableAppoinment);
            JOptionPane.showMessageDialog(null, "Appoinment Created Successfully.");

        } else {
            // if it have empty fields indicate using message
            JOptionPane.showMessageDialog(null, "You have following errors.\n" + errors);
        }
        
        System.out.println(newAvailableAppoinment.getMedical_staff_id()+" | "+newAvailableAppoinment.getDate()+" | "+newAvailableAppoinment.getStartTime()+" | "+newAvailableAppoinment.getEndTime());
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtMedicalStaffIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedicalStaffIdKeyReleased
        String pattern = "^([M][S][0-9]{13})$";
        txtFieldValidation(txtMedicalStaffId, pattern, newAvailableAppoinment, "setMedical_staff_id");
    }//GEN-LAST:event_txtMedicalStaffIdKeyReleased

    private void txtStartTimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStartTimeKeyReleased
        String pattern = "^(([0,1][0-9][:][0-5][0-9])||([2][0-3][:][0-5][0-9]))$";
        txtFieldValidation(txtStartTime, pattern, newAvailableAppoinment, "setStartTime");
    }//GEN-LAST:event_txtStartTimeKeyReleased

    private void txtEndTImeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEndTImeKeyReleased
        String pattern = "^(([0,1][0-9][:][0-5][0-9])||([2][0-3][:][0-5][0-9]))$";
        txtFieldValidation(txtEndTIme, pattern, newAvailableAppoinment, "setEndTime");
    }//GEN-LAST:event_txtEndTImeKeyReleased

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        ImageIcon icon = new ImageIcon("D:\\Projects\\COST Project\\MedicalCenterManagementSystem\\src\\images\\icons\\warning.png");
        //        int res = JOptionPane.showConfirmDialog(null, "Are you sure to exit ?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
        int res = JOptionPane.showConfirmDialog(null, "Are you sure to exit ?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, icon);
        if (res == 0) {
            System.exit(res);
        } else if (res == 1) {
            //         System.out.println("Pressed NO");
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        ImageIcon icon = new ImageIcon("D:\\Projects\\COST Project\\MedicalCenterManagementSystem\\src\\images\\icons\\logout 50.png");
        //        int res = JOptionPane.showConfirmDialog(null, "Are you sure to exit ?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
        int res = JOptionPane.showConfirmDialog(null, "Are you sure to Log Out ?", "Log Out", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, icon);
        if (res == 0) {
            new LogInForm().setVisible(true);
            this.dispose();
        } else if (res == 1) {
            //         System.out.println("Pressed NO");
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        if (userRole.equals("reception")) {

            new HomeFormReceptionist().setVisible(true);
            this.dispose();

        } else if (userRole.equals("doctor")) {

            new HomeFormDoctor().setVisible(true);
            this.dispose();

        } else if (userRole.equals("admin")) {

            new HomeForm().setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_btnHomeActionPerformed

    private String checkErrors(AvailableAppoinment appoinment) {

        String errors = "";

        if (appoinment.getMedical_staff_id().equals("")) {
            errors += "medical staff id not entered.\n";
        }
        if (appoinment.getDate().equals("")) {
            errors += "Date not entered.\n";
        }
        if (appoinment.getStartTime()== "null") {
            errors += "Start time not entered.\n";
        }
        if (appoinment.getEndTime()== "null") {
            errors += "End time not entered.\n";
        }
        return errors;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        FlatIntelliJLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createAppoinment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImage;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtEndTIme;
    private javax.swing.JTextField txtMedicalStaffId;
    private javax.swing.JTextField txtStartTime;
    // End of variables declaration//GEN-END:variables
}
