/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

import appoinment.AddAppoinment;
import com.formdev.flatlaf.FlatIntelliJLaf;
import hospital.HospitalDetailsForm;
import static java.lang.Thread.sleep;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logIn.LogInForm;
import logIn.UserDao;
import patient.PatientRegForm;

/**
 *
 * @author Achinthya Dulshan
 */
public class HomeFormReceptionist extends javax.swing.JFrame {

    /**
     * Creates new form HomeFormReceptionist
     */
    public HomeFormReceptionist() {
        initComponents();
        txtUserName.setText(UserDao.logInUser.getUserName());
        clock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUserName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jSeparator1 = new javax.swing.JSeparator();
        txtDate = new javax.swing.JLabel();
        btnPatient = new javax.swing.JButton();
        btnAppoinments = new javax.swing.JButton();
        btnHospital = new javax.swing.JButton();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUserName.setBackground(new java.awt.Color(255, 255, 255));
        txtUserName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(0, 0, 0));
        txtUserName.setText("Reception");
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, -120, 120, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/receptionist 50.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 30, 50, 50));

        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setText("Medical Center Management System");
        headerPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 228, -1));

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/close.png"))); // NOI18N
        btnClose.setToolTipText("Close Application");
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        headerPanel.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 30, 30));

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/logout.png"))); // NOI18N
        btnLogOut.setToolTipText("Log out");
        btnLogOut.setBorder(null);
        btnLogOut.setBorderPainted(false);
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        headerPanel.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 30, 30));

        getContentPane().add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 30));

        jCalendar1.setDecorationBordersVisible(true);
        getContentPane().add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 150, 260, 200));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 900, 10));

        txtDate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtDate.setForeground(new java.awt.Color(0, 0, 0));
        txtDate.setText("2023/10/06  10.33.40");
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 100, -1, -1));

        btnPatient.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/patient.png"))); // NOI18N
        btnPatient.setText(" Patients");
        btnPatient.setToolTipText("View Patient Details");
        btnPatient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPatientMouseClicked(evt);
            }
        });
        btnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientActionPerformed(evt);
            }
        });
        getContentPane().add(btnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 250, 70));

        btnAppoinments.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnAppoinments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/healthcare.png"))); // NOI18N
        btnAppoinments.setText(" Appoinments");
        btnAppoinments.setToolTipText("View Appoinment Details");
        btnAppoinments.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAppoinments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppoinmentsActionPerformed(evt);
            }
        });
        getContentPane().add(btnAppoinments, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 250, 70));

        btnHospital.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/redCross.png"))); // NOI18N
        btnHospital.setText(" Hospitals");
        btnHospital.setToolTipText("View Hospital Details");
        btnHospital.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHospitalMouseClicked(evt);
            }
        });
        getContentPane().add(btnHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 250, 70));

        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrounds/receptionistHomePanel.png"))); // NOI18N
        getContentPane().add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void clock() {
        Thread clock = new Thread() {
            public void run() {
                try {
                    while (true) {
                        Calendar cal = new GregorianCalendar();
//                         int day=cal.get(Calendar.DAY_OF_MONTH);
//                         int month=cal.get(Calendar.MONTH)+1;
//                         int year=cal.get(Calendar.YEAR);                   
                        int second = cal.get(Calendar.SECOND);
                        int minute = cal.get(Calendar.MINUTE);
                        int hour = cal.get(Calendar.HOUR);

                        DateTimeFormatter date = DateTimeFormatter.ofPattern("yyyy/MM/dd  HH:mm:ss ");
//                        SimpleDateFormat date = new SimpleDateFormat("yyyy/MM/dd  hh:mm aa"); 
                        LocalDateTime now = LocalDateTime.now();

//                        txtTime.setText(hour + ":" + minute + ":" + second);
                        txtDate.setText(date.format(now));
//                    txtDate.setText( year +"-"+ month +"-"+ day );
                        //  getTime=lbltime.getText();
                        // getDate=lbldate.getText();
                        sleep(1000);
                    }
                } catch (Exception e) {
//                    JOptionPane.showMessageDialog(rootPane, e);

                }
            }
        };
        clock.start();
    }
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        ImageIcon icon = new ImageIcon("D:\\Projects\\COST Project\\MedicalCenterManagementSystem\\src\\images\\icons\\warning.png");
        //        int res = JOptionPane.showConfirmDialog(null, "Are you sure to exit ?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
        int res = JOptionPane.showConfirmDialog(null, "Are you sure to exit ?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, icon);
        if (res == 0) {
            System.exit(res);
        } else if (res == 1) {
            //         System.out.println("Pressed NO");
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        ImageIcon icon = new ImageIcon("D:\\Projects\\COST Project\\MedicalCenterManagementSystem\\src\\images\\icons\\logout 50.png");
        //        int res = JOptionPane.showConfirmDialog(null, "Are you sure to exit ?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
        int res = JOptionPane.showConfirmDialog(null, "Are you sure to Log Out ?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, icon);
        if (res == 0) {
            new LogInForm().setVisible(true);
            this.dispose();
        } else if (res == 1) {
            //         System.out.println("Pressed NO");
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPatientMouseClicked

    }//GEN-LAST:event_btnPatientMouseClicked

    private void btnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientActionPerformed
        PatientRegForm newPatientRegForm = new PatientRegForm();
        newPatientRegForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPatientActionPerformed

    private void btnAppoinmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppoinmentsActionPerformed

        AddAppoinment newAddAppoinment = new AddAppoinment();
        newAddAppoinment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAppoinmentsActionPerformed

    private void btnHospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHospitalMouseClicked
        HospitalDetailsForm newhospitalDetails = new HospitalDetailsForm();
        newhospitalDetails.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnHospitalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatIntelliJLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFormReceptionist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImage;
    private javax.swing.JButton btnAppoinments;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHospital;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPatient;
    private javax.swing.JPanel headerPanel;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtUserName;
    // End of variables declaration//GEN-END:variables
}
