/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

import appoinment.ViewAppoinments;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import doctor.DoctorDetailsForm;
import hospital.HospitalDetailsForm;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import patient.PatientDetailsForm;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logIn.LogInForm;
import logIn.UserDao;
import medicalRecords.ViewMedicalRecords;

/**
 *
 * @author Achinthya Dulshan
 */
public class HomeForm extends javax.swing.JFrame {

    /**
     * Creates new form HomeForm
     */
    public HomeForm() {
        initComponents();
        clock();
         txtUserName.setText(UserDao.logInUser.getUserName());
//        DateTimeFormatter date = DateTimeFormatter.ofPattern("yyyy/MM/dd");
//        LocalDateTime now = LocalDateTime.now();
////        System.out.println(dtf.format(now));
//        txtDate.setText(date.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        txtDate = new javax.swing.JLabel();
        btnPatient = new javax.swing.JButton();
        btnDoctor = new javax.swing.JButton();
        btnHospital = new javax.swing.JButton();
        btnAppoinments = new javax.swing.JButton();
        btnMedicalRecords = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        txtUserName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setText("Medical Center Management System");
        headerPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 228, -1));

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/close.png"))); // NOI18N
        btnClose.setToolTipText("Close Application");
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        headerPanel.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 30, 30));

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/logout.png"))); // NOI18N
        btnLogOut.setToolTipText("Log out");
        btnLogOut.setBorder(null);
        btnLogOut.setBorderPainted(false);
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        headerPanel.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 30, 30));

        getContentPane().add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 30));

        txtDate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtDate.setForeground(new java.awt.Color(0, 0, 0));
        txtDate.setText("2023/10/06  10.33.40");
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 120, -1, -1));

        btnPatient.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/patient.png"))); // NOI18N
        btnPatient.setText(" Patients");
        btnPatient.setToolTipText("View Patient Details");
        btnPatient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPatientMouseClicked(evt);
            }
        });
        btnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientActionPerformed(evt);
            }
        });
        getContentPane().add(btnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 250, 70));

        btnDoctor.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/doctor.png"))); // NOI18N
        btnDoctor.setText(" Doctors");
        btnDoctor.setToolTipText("View Doctor Details");
        btnDoctor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoctorMouseClicked(evt);
            }
        });
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 250, 70));

        btnHospital.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/redCross.png"))); // NOI18N
        btnHospital.setText(" Hospitals");
        btnHospital.setToolTipText("View Hospital Details");
        btnHospital.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHospitalMouseClicked(evt);
            }
        });
        getContentPane().add(btnHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 250, 70));

        btnAppoinments.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnAppoinments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/healthcare.png"))); // NOI18N
        btnAppoinments.setText(" Appoinments");
        btnAppoinments.setToolTipText("View Appoinment Details");
        btnAppoinments.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAppoinments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppoinmentsActionPerformed(evt);
            }
        });
        getContentPane().add(btnAppoinments, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 250, 70));

        btnMedicalRecords.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnMedicalRecords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/records.png"))); // NOI18N
        btnMedicalRecords.setText(" Medical Records");
        btnMedicalRecords.setToolTipText("View Medical Records");
        btnMedicalRecords.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMedicalRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicalRecordsActionPerformed(evt);
            }
        });
        getContentPane().add(btnMedicalRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 250, 70));

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton1.setText("No of Doctors We have");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 320, 230));
        getContentPane().add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1092, 170, 260, 200));

        txtUserName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(0, 0, 0));
        txtUserName.setText("admin");
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 50, 80, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/admin 50.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 40, 50, 50));

        jSeparator1.setForeground(new java.awt.Color(0, 204, 204));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 890, 10));

        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrounds/adminHome.png"))); // NOI18N
        getContentPane().add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void clock() {
        Thread clock = new Thread() {
            public void run() {
                try {
                    while (true) {
                        Calendar cal = new GregorianCalendar();
//                         int day=cal.get(Calendar.DAY_OF_MONTH);
//                         int month=cal.get(Calendar.MONTH)+1;
//                         int year=cal.get(Calendar.YEAR);                   
                        int second = cal.get(Calendar.SECOND);
                        int minute = cal.get(Calendar.MINUTE);
                        int hour = cal.get(Calendar.HOUR);

                        DateTimeFormatter date = DateTimeFormatter.ofPattern("yyyy/MM/dd  HH:mm:ss ");
//                        SimpleDateFormat date = new SimpleDateFormat("yyyy/MM/dd  hh:mm aa"); 
                        LocalDateTime now = LocalDateTime.now();

//                        txtTime.setText(hour + ":" + minute + ":" + second);
                        txtDate.setText(date.format(now));
//                    txtDate.setText( year +"-"+ month +"-"+ day );
                        //  getTime=lbltime.getText();
                        // getDate=lbldate.getText();
                        sleep(1000);
                    }
                } catch (Exception e) {
//                    JOptionPane.showMessageDialog(rootPane, e);

                }
            }
        };
        clock.start();
    }
    private void btnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPatientActionPerformed

    private void btnPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPatientMouseClicked
        new PatientDetailsForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPatientMouseClicked

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        new DoctorDetailsForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDoctorActionPerformed

    private void btnHospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHospitalMouseClicked
        new HospitalDetailsForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHospitalMouseClicked

    private void btnDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoctorMouseClicked
        new DoctorDetailsForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDoctorMouseClicked

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        ImageIcon icon = new ImageIcon("D:\\Projects\\COST Project\\MedicalCenterManagementSystem\\src\\images\\icons\\warning.png");
//        int res = JOptionPane.showConfirmDialog(null, "Are you sure to exit ?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
        int res = JOptionPane.showConfirmDialog(null, "Are you sure to exit ?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, icon);
      if(res == 0) {
         System.exit(res);
      } else if (res == 1) {
//         System.out.println("Pressed NO");
      }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        ImageIcon icon = new ImageIcon("D:\\Projects\\COST Project\\MedicalCenterManagementSystem\\src\\images\\icons\\logout 50.png");
//        int res = JOptionPane.showConfirmDialog(null, "Are you sure to exit ?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
        int res = JOptionPane.showConfirmDialog(null, "Are you sure to Log Out ?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, icon);
      if(res == 0) {
         new LogInForm().setVisible(true);
         this.dispose();
      } else if (res == 1) {
//         System.out.println("Pressed NO");
      }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnMedicalRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicalRecordsActionPerformed
        new ViewMedicalRecords().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnMedicalRecordsActionPerformed

    private void btnAppoinmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppoinmentsActionPerformed
        new ViewAppoinments().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnAppoinmentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        FlatIntelliJLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImage;
    private javax.swing.JButton btnAppoinments;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDoctor;
    private javax.swing.JButton btnHospital;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMedicalRecords;
    private javax.swing.JButton btnPatient;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtUserName;
    // End of variables declaration//GEN-END:variables
}
