/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loader;

import logIn.LogInForm;
/**
 *
 * @author Achinthya Dulshan
 */
public class Loader extends javax.swing.JFrame {

    /**
     * Creates new form Loader
     */
    public Loader() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loaderHeader = new javax.swing.JLabel();
        loaderProgress = new javax.swing.JProgressBar();
        loaderPercentage = new javax.swing.JLabel();
        loaderBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loaderHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        loaderHeader.setForeground(new java.awt.Color(255, 255, 255));
        loaderHeader.setText("Medical Center Management System (MCMS)");
        jPanel1.add(loaderHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        loaderProgress.setBackground(new java.awt.Color(25, 123, 48));
        loaderProgress.setForeground(new java.awt.Color(255, 255, 255));
        loaderProgress.setBorder(null);
        loaderProgress.setBorderPainted(false);
        loaderProgress.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(loaderProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 600, 10));

        loaderPercentage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loaderPercentage.setForeground(new java.awt.Color(255, 255, 255));
        loaderPercentage.setText("%");
        jPanel1.add(loaderPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        loaderBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loader.png"))); // NOI18N
        jPanel1.add(loaderBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Loader().setVisible(true);
//            }
//        });

            Loader loaderObj = new Loader();
            loaderObj.setVisible(true);
            try{
            
                for(int i=0;i<=100;i+=2){
                    Thread.sleep(100);
                    loaderObj.loaderProgress.setValue(i);
                    loaderObj.loaderPercentage.setText(i+" %");
                }
            }catch(Exception e){
            }
            new LogInForm().setVisible(true);
            loaderObj.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loaderBg;
    private javax.swing.JLabel loaderHeader;
    private javax.swing.JLabel loaderPercentage;
    private javax.swing.JProgressBar loaderProgress;
    // End of variables declaration//GEN-END:variables
}
