/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appoinment;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import doctor.Doctor;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import static patient.PatientRegForm.invalidBorder;
import static patient.PatientRegForm.validBorder;

/**
 *
 * @author Achinthya Dulshan
 */
public class AddAppoinment extends javax.swing.JFrame {

    private AppoinmentDao dao;
    private DefaultComboBoxModel<String> comboBoxModel;
    private AvailableAppoinmentDao appoinmentDao;
    private Appoinment appoinment;

    /**
     * Creates new form AddAppoinment
     */
    public AddAppoinment() {
        initComponents();
        dao = new AppoinmentDao();
        appoinmentDao = new AvailableAppoinmentDao();
        appoinment = new Appoinment();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        selectDoctorType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        selectDoctor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        selectTimeSlot = new javax.swing.JComboBox<>();
        txtPatientId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        btnAddAppoinment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Medical Center Management System");
        headerPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 228, -1));

        btnClose.setBackground(new java.awt.Color(255, 0, 0));
        btnClose.setIcon(new javax.swing.ImageIcon("C:\\Users\\Achinthya Dulshan\\Downloads\\close re.png")); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        headerPanel.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 30, 30));

        jPanel1.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 30));

        jLabel2.setText("Select Type:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        selectDoctorType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select the type of Doctor", "General Practitioner (GP) or Family Physician", "Otolaryngologist (ENT Specialist)", "Neurologist", "Dermatologist", "Cardiologist" }));
        selectDoctorType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDoctorTypeActionPerformed(evt);
            }
        });
        jPanel1.add(selectDoctorType, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 170, -1));

        jLabel3.setText("Select Doctor:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        selectDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select the Doctor" }));
        selectDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDoctorActionPerformed(evt);
            }
        });
        jPanel1.add(selectDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 300, 30));

        jLabel4.setText("Select Time Slot:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 100, -1));

        selectTimeSlot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Time Slot" }));
        selectTimeSlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTimeSlotActionPerformed(evt);
            }
        });
        jPanel1.add(selectTimeSlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 410, 30));

        txtPatientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtPatientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 200, -1));

        jLabel5.setText("Patient ID:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 70, -1));

        jLabel6.setText("notes:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        jScrollPane1.setViewportView(txtNotes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        btnAddAppoinment.setText("Add Appoinment");
        btnAddAppoinment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAppoinmentActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddAppoinment, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed

    }//GEN-LAST:event_btnCloseActionPerformed

    private void selectDoctorTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDoctorTypeActionPerformed
        String selectedOption = selectDoctorType.getSelectedItem().toString();

        comboBoxModel = new DefaultComboBoxModel<>();
        comboBoxModel.addElement("Select Doctor");
        selectDoctor.setModel(comboBoxModel);

//        DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) selectDoctor.getModel();
        System.out.println("doc type" + selectedOption);

        if (selectedOption.equals("Select the type of Doctor")) {
            JOptionPane.showMessageDialog(this, "Invalid Selection.");
        } else {
            String viewingDoctor = "";
            ArrayList<ArrayList<String>> selectedDoctors = dao.getDoctorsByType(selectedOption);
//            String doctorsList[] = new String[selectedDoctors.size()];
            if (selectedDoctors == null) {
                JOptionPane.showMessageDialog(this, "There are no Doctors with this type.");
            } else {
                for (ArrayList<String> selectedDoctor : selectedDoctors) {
                    viewingDoctor = selectedDoctor.get(0) + " | " + selectedDoctor.get(1) + " " + selectedDoctor.get(2);
                    comboBoxModel.addElement(viewingDoctor);
                }
            }
        }
    }//GEN-LAST:event_selectDoctorTypeActionPerformed

    private void selectDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDoctorActionPerformed
        String selectedOption = selectDoctor.getSelectedItem().toString();

        comboBoxModel = new DefaultComboBoxModel<>();
        comboBoxModel.addElement("Select time Slot");
        selectTimeSlot.setModel(comboBoxModel);

        System.out.println();
        ArrayList<ArrayList<String>> appoinmentList = appoinmentDao.getAvailableAppoinmentDetails(selectedOption.split(" | ")[0].trim());

        if (selectedOption.equals("Select time Slot")) {
            JOptionPane.showMessageDialog(this, "Invalid Selection.");
        } else {
            String availableSlot = "";

            if (appoinmentList == null) {
                JOptionPane.showMessageDialog(this, "Not available time slots.");
            } else {
                for (ArrayList<String> availableAppoinment : appoinmentList) {
                    System.out.println("a" + availableAppoinment);
                    availableSlot = availableAppoinment.get(1) + " | " + availableAppoinment.get(2) + " from " + availableAppoinment.get(3) + " to " + availableAppoinment.get(4);
                    comboBoxModel.addElement(availableSlot);
                }
            }
        }
    }//GEN-LAST:event_selectDoctorActionPerformed

    private void selectTimeSlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTimeSlotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectTimeSlotActionPerformed

    private void txtPatientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientIdActionPerformed

    private void btnAddAppoinmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAppoinmentActionPerformed

        if (txtPatientId.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Patient ID not entered");
        } else {
            appoinment.setPatient_id(txtPatientId.getText());

            if (txtNotes.getText().equals("")) {
                appoinment.setNotes("-");
            } else {
                appoinment.setNotes(txtNotes.getText());
            }

            appoinment.setStatus("Active");
            appoinment.setMedical_staff_id(selectDoctor.getSelectedItem().toString().split(" | ")[0].trim());
            appoinment.setAvailable_appoinment_id(selectTimeSlot.getSelectedItem().toString().split(" | ")[0].trim());
        }

        dao.addAppoinment(appoinment);

    }//GEN-LAST:event_btnAddAppoinmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        FlatIntelliJLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAppoinment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAppoinment;
    private javax.swing.JButton btnClose;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selectDoctor;
    private javax.swing.JComboBox<String> selectDoctorType;
    private javax.swing.JComboBox<String> selectTimeSlot;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtPatientId;
    // End of variables declaration//GEN-END:variables
}
