/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appoinment;

import availableAppoinments.createAppoinment;
import com.formdev.flatlaf.FlatIntelliJLaf;
import home.HomeForm;
import home.HomeFormDoctor;
import home.HomeFormReceptionist;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logIn.LogInForm;
import logIn.UserDao;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Achinthya Dulshan
 */
public class ViewAppoinments extends javax.swing.JFrame {

    private AppoinmentDao dao;
    private String userRole = UserDao.logInUser.getRole();
    /**
     * Creates new form ViewAppoinments
     */
    public ViewAppoinments() {
        initComponents();
        dao = new AppoinmentDao();
        loadTable();
        checkPrivillage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        appoinmentDetailsTable = new javax.swing.JTable();
        headerPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnAddAppoinment = new javax.swing.JButton();
        btnCreateAppoinment = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Appoinment Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 340, 50));

        jSeparator1.setForeground(new java.awt.Color(255, 204, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 990, 10));

        appoinmentDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        appoinmentDetailsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appoinmentDetailsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(appoinmentDetailsTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 1030, 480));

        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel10.setText("Medical Center Management System");
        headerPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 228, -1));

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/close.png"))); // NOI18N
        btnClose.setToolTipText("Close Application");
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        headerPanel.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 30, 30));

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/logout.png"))); // NOI18N
        btnLogOut.setToolTipText("Log out");
        btnLogOut.setBorder(null);
        btnLogOut.setBorderPainted(false);
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        headerPanel.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 30, 30));

        getContentPane().add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 30));

        btnAddAppoinment.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnAddAppoinment.setText("Add Appoinment");
        btnAddAppoinment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAppoinmentActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddAppoinment, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 180, 50));

        btnCreateAppoinment.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnCreateAppoinment.setText("Create Appoinment");
        btnCreateAppoinment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAppoinmentActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreateAppoinment, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 180, 50));

        btnHome.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/home.png"))); // NOI18N
        btnHome.setText(" Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 180, 50));

        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrounds/appoinmenDetails.png"))); // NOI18N
        getContentPane().add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkPrivillage() {
        if (userRole.equals("reception")) {
//            btnShowPatientDetails.setVisible(false);
        }
    }
    
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        ImageIcon icon = new ImageIcon("D:\\Projects\\COST Project\\MedicalCenterManagementSystem\\src\\images\\icons\\warning.png");
        //        int res = JOptionPane.showConfirmDialog(null, "Are you sure to exit ?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
        int res = JOptionPane.showConfirmDialog(null, "Are you sure to exit ?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, icon);
        if(res == 0) {
            System.exit(res);
        } else if (res == 1) {
            //         System.out.println("Pressed NO");
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        ImageIcon icon = new ImageIcon("D:\\Projects\\COST Project\\MedicalCenterManagementSystem\\src\\images\\icons\\logout 50.png");
        //        int res = JOptionPane.showConfirmDialog(null, "Are you sure to exit ?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
        int res = JOptionPane.showConfirmDialog(null, "Are you sure to Log Out ?", "Log Out", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, icon);
        if(res == 0) {
            new LogInForm().setVisible(true);
            this.dispose();
        } else if (res == 1) {
            //         System.out.println("Pressed NO");
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        if (userRole.equals("reception")) {

            new HomeFormReceptionist().setVisible(true);
            this.dispose();

        } else if (userRole.equals("doctor")) {

            new HomeFormDoctor().setVisible(true);
            this.dispose();

        } else if (userRole.equals("admin")) {

            new HomeForm().setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAddAppoinmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAppoinmentActionPerformed
        new AddAppoinment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddAppoinmentActionPerformed

    private void btnCreateAppoinmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAppoinmentActionPerformed
        new createAppoinment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCreateAppoinmentActionPerformed

    private void appoinmentDetailsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appoinmentDetailsTableMouseClicked
        int selectedRow = appoinmentDetailsTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) appoinmentDetailsTable.getModel();
        new ShowAppoinment().fillDataToFrame(model, selectedRow);
    }//GEN-LAST:event_appoinmentDetailsTableMouseClicked

    private void loadTable() {
        ResultSet rs = dao.fillTableData();
        appoinmentDetailsTable.setModel(DbUtils.resultSetToTableModel(rs));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatIntelliJLaf.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAppoinments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable appoinmentDetailsTable;
    private javax.swing.JLabel bgImage;
    private javax.swing.JButton btnAddAppoinment;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCreateAppoinment;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
