/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medicalRecords;

import com.toedter.calendar.JDateChooser;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import prescription.Prescription;
import prescription.PrescriptionController;
import prescription.PrescriptionDao;

/**
 *
 * @author Achinthya Dulshan
 */
public class AddMedicalRecord extends javax.swing.JFrame {

    private MedicalRecordDao recordDao;
    private PrescriptionDao prescriptionDao;
    private Prescription newPrescription;
    private MedicalRecord newRecord;
    File newPrescriptionFile;
    ArrayList<ArrayList<String>> medicationsArray;

    /**
     * Creates new form AddMedicalRecord
     */
    public AddMedicalRecord() {
        initComponents();
        newRecord = new MedicalRecord();
        recordDao = new MedicalRecordDao();
        prescriptionDao = new PrescriptionDao();
        newPrescription = new Prescription();
        medicationsArray = new ArrayList<ArrayList<String>>();
        newPrescriptionFile = new PrescriptionController().createPrescription();
        newRecord.setPrescriptionId(prescriptionDao.getPrescriptionId());
        newPrescription.setLink(newPrescriptionFile.getAbsolutePath());
//        prescrptionDataEnterPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDiagnosis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTreatmentPlan = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTestResults = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtPatientId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDoctorId = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnSubmit = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        prescriptionViewPanel = new javax.swing.JPanel();
        prescrptionDataEnterPanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        endDate = new com.toedter.calendar.JDateChooser();
        startDate = new com.toedter.calendar.JDateChooser();
        txtMedicationName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDosage = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnPrescription = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Medical Center Management System");
        headerPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 228, -1));

        btnClose.setBackground(new java.awt.Color(255, 0, 0));
        btnClose.setIcon(new javax.swing.ImageIcon("C:\\Users\\Achinthya Dulshan\\Downloads\\close re.png")); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        headerPanel.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 30, 30));

        mainPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 30));

        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Diagnosis");
        contentPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 20));
        contentPanel.add(txtDiagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 230, -1));

        jLabel3.setText("Treatment Plan");
        contentPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 90, -1));

        txtTreatmentPlan.setColumns(20);
        txtTreatmentPlan.setRows(5);
        jScrollPane1.setViewportView(txtTreatmentPlan);

        contentPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 310, 50));

        jLabel4.setText("Test Results");
        contentPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        txtTestResults.setColumns(20);
        txtTestResults.setRows(5);
        jScrollPane2.setViewportView(txtTestResults);

        contentPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 310, 50));

        jLabel5.setText("Patient ID");
        contentPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        contentPanel.add(txtPatientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 170, -1));

        jLabel6.setText("Doctor ID");
        contentPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));
        contentPanel.add(txtDoctorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 190, -1));
        contentPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 440, 20));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        contentPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 20, 500));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        contentPanel.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, -1, -1));

        btnPrint.setText("Print");
        contentPanel.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, -1, -1));

        prescriptionViewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        contentPanel.add(prescriptionViewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 420, 460));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtMedicationName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicationNameActionPerformed(evt);
            }
        });

        jLabel7.setText("Medication Name");

        jLabel10.setText("End Date");

        jLabel8.setText("Dosage");

        jLabel9.setText("Start Date");

        javax.swing.GroupLayout prescrptionDataEnterPanelLayout = new javax.swing.GroupLayout(prescrptionDataEnterPanel);
        prescrptionDataEnterPanel.setLayout(prescrptionDataEnterPanelLayout);
        prescrptionDataEnterPanelLayout.setHorizontalGroup(
            prescrptionDataEnterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(prescrptionDataEnterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(prescrptionDataEnterPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(prescrptionDataEnterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(prescrptionDataEnterPanelLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(15, 15, 15)
                            .addComponent(txtMedicationName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(prescrptionDataEnterPanelLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(69, 69, 69)
                            .addComponent(txtDosage, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(prescrptionDataEnterPanelLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(46, 46, 46)
                            .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(jLabel10)
                            .addGap(31, 31, 31)
                            .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(prescrptionDataEnterPanelLayout.createSequentialGroup()
                            .addGap(290, 290, 290)
                            .addComponent(btnAdd)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        prescrptionDataEnterPanelLayout.setVerticalGroup(
            prescrptionDataEnterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(prescrptionDataEnterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(prescrptionDataEnterPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(prescrptionDataEnterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(txtMedicationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(14, 14, 14)
                    .addGroup(prescrptionDataEnterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(txtDosage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(14, 14, 14)
                    .addGroup(prescrptionDataEnterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(prescrptionDataEnterPanelLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel10))
                        .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addComponent(btnAdd)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        contentPanel.add(prescrptionDataEnterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        btnPrescription.setText("Prescription");
        btnPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrescriptionActionPerformed(evt);
            }
        });
        contentPanel.add(btnPrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        mainPanel.add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 900, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed

    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtMedicationNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicationNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicationNameActionPerformed
    private String checkPrescriptionErrors(Prescription prescription) {

        String errors = "";

        if (prescription.getMedicationName().equals("")) {
            errors += "medication name not entered.\n";
        }
        if (prescription.getDosage().equals("")) {
            errors += "Dosage not entered.\n";
        }
        if (prescription.getStartDate() == "null") {
            errors += "Start date not entered.\n";
        }
        if (prescription.getEndDate() == "null") {
            errors += "End date not entered.\n";
        }
        return errors;
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        newPrescription.setMedicationName(txtMedicationName.getText());
        newPrescription.setDosage(txtDosage.getText());
        newPrescription.setStartDate(getSelectedDate(startDate));
        newPrescription.setEndDate(getSelectedDate(endDate));
        

        String errors = checkPrescriptionErrors(newPrescription);

        if (errors.equals("")) {
            medicationsArray.add(new ArrayList<>(Arrays.asList(txtMedicationName.getText(), txtDosage.getText(), getSelectedDate(startDate), getSelectedDate(endDate))));

            JOptionPane.showMessageDialog(this, "medication " + txtMedicationName.getText() + " added Successfully");

            txtMedicationName.setText("");
            txtDosage.setText("");

            Date date = new Date();
            startDate.setDate(date);
            endDate.setDate(date);
        } else {
            JOptionPane.showMessageDialog(this, "You have following errors.\n" + errors);
        }


    }//GEN-LAST:event_btnAddActionPerformed

    //format entered date 
    private String getSelectedDate(JDateChooser datachooser) {
        Date date = datachooser.getDate();
        if (date == null) {
            return "null";
        } else {
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            String strDate = formatter.format(date);
            return strDate;
        }
    }
    private void btnPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrescriptionActionPerformed
//        File newPrescriptionFile = new PrescriptionController().createPrescription();
//        prescrptionDataEnterPanel.setVisible(true);

        try {
            FileWriter newWriter = new FileWriter(newPrescriptionFile);
            newWriter.write("********* PRESCRIPTION *********\n");
            newWriter.write("Date and Time : " + getDateAndTime() + "\n");
            newWriter.write("Doctor Name : " + "name of doctor" + "\n\n");
            newWriter.write("====================================\n");
            newWriter.write("| Medication | Dosage | Start date | End date |\n");

            for (ArrayList<String> arrayList : medicationsArray) {
                newWriter.write(" - ");
                for (String string : arrayList) {
                    newWriter.write(string + " | ");
                }
                newWriter.write("\n");
            }

            newWriter.close();
        } catch (IOException ex) {
            Logger.getLogger(AddMedicalRecord.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnPrescriptionActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        
        newRecord.setPatient_id(txtPatientId.getText());
        newRecord.setMedical_staff_id(txtDoctorId.getText());
        newRecord.setDiagnosis(txtDiagnosis.getText());
        newRecord.setTratmentPlan(txtTreatmentPlan.getText());
        newRecord.setTestResult(txtTestResults.getText());
        
        
        prescriptionDao.insertPrescription(newPrescription);
        recordDao.insertMedicalRecord(newRecord);
        
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private String getDateAndTime() {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();

        return dtf.format(now);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMedicalRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMedicalRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMedicalRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMedicalRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMedicalRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnPrescription;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JPanel contentPanel;
    private com.toedter.calendar.JDateChooser endDate;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel prescriptionViewPanel;
    private javax.swing.JPanel prescrptionDataEnterPanel;
    private com.toedter.calendar.JDateChooser startDate;
    private javax.swing.JTextField txtDiagnosis;
    private javax.swing.JTextField txtDoctorId;
    private javax.swing.JTextField txtDosage;
    private javax.swing.JTextField txtMedicationName;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextArea txtTestResults;
    private javax.swing.JTextArea txtTreatmentPlan;
    // End of variables declaration//GEN-END:variables
}
