/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package doctor;

import home.HomeForm;
import java.awt.Color;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author Achinthya Dulshan
 */
public class DoctorRegForm extends javax.swing.JFrame {

    DoctorDao doctorDao;

    //define static variables for future refrence
    private static DoctorRegForm updatingDoctorForm;
    private static Doctor updatingDoctor;
    private static Doctor doctor;

    //define validation borders
    public static Border invalidBorder = new LineBorder(Color.red, 2, true);
    public static Border validBorder = new LineBorder(Color.GREEN, 2, true);

    //default constructor
    public DoctorRegForm() {
        initComponents();
        // init doctorDao object
        doctorDao = new DoctorDao();
        // init doctor object 
        doctor = new Doctor();

        // set update button invisible
        btnUpdate.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        headerText = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        footerText = new javax.swing.JLabel();
        mainDataPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        selectGender = new javax.swing.JComboBox<>();
        txtContact_1 = new javax.swing.JTextField();
        txtContact_2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        formHeading = new javax.swing.JLabel();
        txtSpecialization = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtLicenseNo = new javax.swing.JTextField();
        txtDateofBirth = new com.toedter.calendar.JDateChooser();
        navPanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnShowDoctorDetails = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnReturnToHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(25, 123, 48));

        headerText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        headerText.setForeground(new java.awt.Color(255, 255, 255));
        headerText.setText("Medical Center Management System (MCMS)");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(headerText, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(headerText)
                .addGap(33, 33, 33))
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 100));

        footer.setBackground(new java.awt.Color(0, 0, 102));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        footerText.setText("Footer text");
        footer.add(footerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 471, -1));

        getContentPane().add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1000, 20));

        mainDataPanel.setBackground(new java.awt.Color(78, 80, 82));
        mainDataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name :");
        mainDataPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 89, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name :");
        mainDataPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Address :");
        mainDataPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIC :");
        mainDataPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender :");
        mainDataPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date of Birth :");
        mainDataPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contact No :");
        mainDataPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contact No :");
        mainDataPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Specialization :");
        mainDataPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyReleased(evt);
            }
        });
        mainDataPanel.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 210, 30));

        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLastNameKeyReleased(evt);
            }
        });
        mainDataPanel.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 210, 30));

        txtNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNICKeyReleased(evt);
            }
        });
        mainDataPanel.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 210, 30));

        selectGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female" }));
        selectGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectGenderActionPerformed(evt);
            }
        });
        mainDataPanel.add(selectGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 210, 30));

        txtContact_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContact_1KeyReleased(evt);
            }
        });
        mainDataPanel.add(txtContact_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 210, 30));

        txtContact_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContact_2KeyReleased(evt);
            }
        });
        mainDataPanel.add(txtContact_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 210, 30));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        mainDataPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 560, 50));

        formHeading.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        formHeading.setForeground(new java.awt.Color(255, 255, 255));
        formHeading.setText("Doctor Registration");
        mainDataPanel.add(formHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 220, 30));

        txtSpecialization.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSpecializationKeyReleased(evt);
            }
        });
        mainDataPanel.add(txtSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 210, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("License No :");
        mainDataPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        txtLicenseNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLicenseNoKeyReleased(evt);
            }
        });
        mainDataPanel.add(txtLicenseNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 210, 30));
        mainDataPanel.add(txtDateofBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 210, -1));

        getContentPane().add(mainDataPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 720, 530));

        navPanel.setBackground(new java.awt.Color(78, 80, 82));
        navPanel.setForeground(new java.awt.Color(255, 255, 255));
        navPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setBackground(new java.awt.Color(0, 255, 51));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        navPanel.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 200, 40));

        btnShowDoctorDetails.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnShowDoctorDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnShowDoctorDetails.setText("Show Doctor Details");
        btnShowDoctorDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDoctorDetailsActionPerformed(evt);
            }
        });
        navPanel.add(btnShowDoctorDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 250, 40));

        btnUpdate.setBackground(new java.awt.Color(102, 102, 255));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        navPanel.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 200, 40));

        btnReturnToHome.setBackground(new java.awt.Color(255, 197, 62));
        btnReturnToHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReturnToHome.setForeground(new java.awt.Color(255, 255, 255));
        btnReturnToHome.setText("Return to Home");
        btnReturnToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnToHomeActionPerformed(evt);
            }
        });
        navPanel.add(btnReturnToHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 250, 40));

        getContentPane().add(navPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 280, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // when click on Show Patient Details button
    private void btnShowDoctorDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDoctorDetailsActionPerformed
        new DoctorDetailsForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnShowDoctorDetailsActionPerformed

    private void btnReturnToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnToHomeActionPerformed
        //show Home page and close this one
        new HomeForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReturnToHomeActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked

        // setAddress in doctor
        doctor.setAddress(txtAddress.getText());
        // setDateOfBirth in patient
        doctor.setDateOfBirth(getSelectedBirthDate());

        /* when the txtContact_2(optional) field is empty it will store NULL in database, 
        in update this will be an error therefore it set to empty String*/
        if (txtContact_2.getText().equals("")) {
            doctor.setContactNo_2("");
        }

        // checking form has empty fields
        String errors = checkErrors();

        if (errors.equals("")) {

            // if it doesn't have empty field 
            // insert to database and give message
            doctorDao.insertMedicalStaff(doctor);
            JOptionPane.showMessageDialog(this, "Doctor Registered Successfully.");

            new DoctorDetailsForm().setVisible(true);
            this.dispose();
        } else {
            // if it have empty fields indicate using message
            JOptionPane.showMessageDialog(this, "You have following errors.\n" + errors);
        }


    }//GEN-LAST:event_btnAddMouseClicked

    private void txtFirstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyReleased
        String pattern = "^([A-Z][a-z]{3,25})$";
        txtFieldValidation(txtFirstName, pattern, doctor, "setFirstName");
    }//GEN-LAST:event_txtFirstNameKeyReleased

    private void txtLastNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyReleased
        String pattern = "^([A-Z][a-z]{3,25})$";
        txtFieldValidation(txtLastName, pattern, doctor, "setLastName");
    }//GEN-LAST:event_txtLastNameKeyReleased

    private void txtNICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNICKeyReleased
        String pattern = "^([12][09][01789][0-9]{9})|([789][0-9]{8}[V|v])$";
        txtFieldValidation(txtNIC, pattern, doctor, "setNIC");
    }//GEN-LAST:event_txtNICKeyReleased

    private void txtSpecializationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSpecializationKeyReleased
        String pattern = "^(.*)$";
        txtFieldValidation(txtSpecialization, pattern, doctor, "setSpecialization");
    }//GEN-LAST:event_txtSpecializationKeyReleased

    private void txtLicenseNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLicenseNoKeyReleased
        String pattern = "^(.*)$";
        txtFieldValidation(txtLicenseNo, pattern, doctor, "setLicenseNumber");
    }//GEN-LAST:event_txtLicenseNoKeyReleased

    private void txtContact_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContact_1KeyReleased
        String pattern = "^([0][7][01245678][0-9]{7})|([0][012345689][0-9]{8})$";
        txtFieldValidation(txtContact_1, pattern, doctor, "setContactNo_1");
    }//GEN-LAST:event_txtContact_1KeyReleased

    private void txtContact_2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContact_2KeyReleased
        String pattern = "^([0][7][01245678][0-9]{7})|([0][012345689][0-9]{8})$";
        txtFieldValidation(txtContact_2, pattern, doctor, "setContactNo_2");
    }//GEN-LAST:event_txtContact_2KeyReleased

    //format entered date 
    private String getSelectedBirthDate() {
        Date birthDate = txtDateofBirth.getDate();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        String strBirthDate = formatter.format(birthDate);
        return strBirthDate;
    }

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked

        // get staffId to future refrences
        doctor.setStaffId(updatingDoctor.getStaffId());

        //set values to object
        doctor.setAddress(txtAddress.getText());
        doctor.setDateOfBirth(getSelectedBirthDate());

        // check what values were updated
        String updates = checkUpdates(doctor);

        // check whether reqiured fields have empty values
        String errors = checkErrors();

        if (errors.equals("")) {

            // if required fields are filled
            if (updates == "") {
                // if it doesn't update any value --> show message
                JOptionPane.showMessageDialog(this, "No updates have been done.");

            } else {
                // if it update any value --> show message with updated fields
                int result = JOptionPane.showConfirmDialog(this, updates);

                // Check the user's choice
                if (result == JOptionPane.YES_OPTION) {

                    //perform update & load doctor table
                    doctorDao.updateDoctor(doctor);
                    new DoctorDetailsForm().setVisible(true);
                    this.dispose();

                } else if (result == JOptionPane.NO_OPTION) {

                } else if (result == JOptionPane.CANCEL_OPTION) {

                    //reload Patient details form and abort action
                    new DoctorDetailsForm().setVisible(true);
                    this.dispose();

                } else if (result == JOptionPane.CLOSED_OPTION) {

                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "You have following errors.\n" + errors);
        }

    }//GEN-LAST:event_btnUpdateMouseClicked

    private void selectGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectGenderActionPerformed

        try {
            selectFieldValidation(selectGender, "Select Gender", doctor, "setGender");
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(DoctorRegForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(DoctorRegForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(DoctorRegForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(DoctorRegForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_selectGenderActionPerformed

    public static void txtFieldValidation(JTextField textField, String matchingPattern, Object object, String method) {
        Pattern pattern;
        Matcher isMatching;
        Border invalidBorder = new LineBorder(Color.red, 2, true);
        Border validBorder = new LineBorder(Color.GREEN, 2, true);

        pattern = Pattern.compile(matchingPattern);
        isMatching = pattern.matcher(textField.getText());

        if (isMatching.matches()) {
            textField.setBorder(validBorder);
            try {
                // Method name to be invoked
                String methodName = method;

                // Get the method with the specified name
                Method executingMethod = object.getClass().getDeclaredMethod(methodName, String.class);

                // Invoke the method on the instance
                executingMethod.invoke(object, textField.getText());

            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {
            textField.setBorder(invalidBorder);
        }

    }

    // define method for select field validation
    public static void selectFieldValidation(JComboBox comboBox, String defaultSelectedOption, Object object, String method) throws NoSuchMethodException, IllegalAccessException, IllegalArgumentException, InvocationTargetException {
        String selectedOption = comboBox.getSelectedItem().toString();

        if (selectedOption.equals(defaultSelectedOption)) {
            comboBox.setBorder(invalidBorder);
            // Get the method with the specified name
            Method executingMethod = object.getClass().getDeclaredMethod(method, String.class);

            // Invoke the method on the instance
            executingMethod.invoke(object, null);
        } else {

            comboBox.setBorder(validBorder);

            // Get the method with the specified name
            Method executingMethod = object.getClass().getDeclaredMethod(method, String.class);

            // Invoke the method on the instance
            executingMethod.invoke(object, selectedOption);

        }
    }

    private String checkUpdates(Doctor existingDoctor) {

        String updates = "";

        if (!updatingDoctor.getFirstName().equals(existingDoctor.getFirstName())) {
            updates += "First name Changed. \n";
        }
        if (!updatingDoctor.getLastName().equals(existingDoctor.getLastName())) {
            updates += "Last name Changed. \n";
        }
        if (!updatingDoctor.getAddress().equals(existingDoctor.getAddress())) {
            updates += "Address Changed. \n";
        }
        if (!updatingDoctor.getNIC().equals(existingDoctor.getNIC())) {
            updates += "NIC Changed. \n";
        }
        if (!updatingDoctor.getDateOfBirth().equals(existingDoctor.getDateOfBirth())) {
            updates += "Date of Birth Changed. \n";
        }
        if (!updatingDoctor.getGender().equals(existingDoctor.getGender())) {
            updates += "Gender Changed. \n";
        }
        if (!updatingDoctor.getSpecialization().equals(existingDoctor.getSpecialization())) {
            updates += "Specialization Changed. \n";
        }
        if (!updatingDoctor.getLicenseNumber().equals(existingDoctor.getLicenseNumber())) {
            updates += "License number Changed. \n";
        }
        if (!updatingDoctor.getContactNo_1().equals(existingDoctor.getContactNo_1())) {
            updates += "Contact No:1 Changed. \n";
        }
        if (!updatingDoctor.getContactNo_2().equals(existingDoctor.getContactNo_2())) {
            updates += "Contact No:2 Changed. \n";
        }

        return updates;
    }

    private String checkErrors() {

        String errors = "";

        if (doctor.getFirstName() == null) {
            errors += "First name not entered.\n";
        }
        if (doctor.getLastName() == null) {
            errors += "Last name not entered.\n";
        }
        if (doctor.getAddress() == null) {
            errors += "Address not entered.\n";
        }
        if (doctor.getNIC() == null) {
            errors += "NIC not entered.\n";
        }
        if (doctor.getGender() == null) {
            errors += "Gender not selected.\n";
        }
        if (doctor.getDateOfBirth() == null) {
            errors += "Date of birth not selected.\n";
        }
        if (doctor.getSpecialization() == null) {
            errors += "Specialization not entered.\n";
        }
        if (doctor.getLicenseNumber() == null) {
            errors += "License number not entered.\n";
        }
        if (doctor.getContactNo_1() == null) {
            errors += "Contact No:1 not entered.\n";
        }

        return errors;
    }

    public void updateDoctorDetails(Doctor selectedDoctor) throws ParseException {

        doctor = selectedDoctor;
        updatingDoctor = selectedDoctor;

        if (updatingDoctorForm == null) {
            updatingDoctorForm = new DoctorRegForm();
        }

        System.out.println("name: " + selectedDoctor.getFirstName() + " " + selectedDoctor.getLastName());

        updatingDoctorForm.formHeading.setText("Update Doctor Details");

        updatingDoctorForm.txtFirstName.setText(selectedDoctor.getFirstName());
        updatingDoctorForm.txtLastName.setText(selectedDoctor.getLastName());
        updatingDoctorForm.txtAddress.setText(selectedDoctor.getAddress());
        updatingDoctorForm.txtNIC.setText(selectedDoctor.getNIC());
        updatingDoctorForm.selectGender.setSelectedItem(selectedDoctor.getGender());

        updatingDoctorForm.txtDateofBirth.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(selectedDoctor.getDateOfBirth()));
        updatingDoctorForm.txtSpecialization.setText(selectedDoctor.getSpecialization());
        updatingDoctorForm.txtLicenseNo.setText(selectedDoctor.getLicenseNumber());
        updatingDoctorForm.txtContact_1.setText(selectedDoctor.getContactNo_1());
        updatingDoctorForm.txtContact_2.setText(selectedDoctor.getContactNo_2());

        updatingDoctorForm.btnAdd.setVisible(false);
        updatingDoctorForm.btnUpdate.setVisible(true);

        updatingDoctorForm.setVisible(true);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorRegForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnReturnToHome;
    private javax.swing.JButton btnShowDoctorDetails;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel footer;
    private javax.swing.JLabel footerText;
    private javax.swing.JLabel formHeading;
    private javax.swing.JPanel header;
    private javax.swing.JLabel headerText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainDataPanel;
    private javax.swing.JPanel navPanel;
    private javax.swing.JComboBox<String> selectGender;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtContact_1;
    private javax.swing.JTextField txtContact_2;
    private com.toedter.calendar.JDateChooser txtDateofBirth;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLicenseNo;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtSpecialization;
    // End of variables declaration//GEN-END:variables
}
